
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: Estelle Ladrange — Social Media Manager
subtitle: "Social Media Manager à Toulouse"
url: "https://www.elcm.fr" # the base hostname & protocol for your site
baseurl: ""

# Build settings
markdown: kramdown

